[module/spotify]
type = custom/script
interval = 0.25
format-prefix = " "
format = <label>
exec = python3 /home/nulldomain/.config/polybar/scripts/spotify.py -p ','
format-underline = #1db954
;control players (optional)
click-left = playerctl --player=spotify play-pause 
click-right = playerctl --player=spotify next 
click-middle = playerctl --player=spotify previous

scroll-up = playerctl --player=spotify volume 0.05+
scroll-down = playerctl --player=spotify volume 0.05-
